Drop table if exists bookings;
Drop table if exists requests;
Drop table if exists comments;
Drop table if exists items;
Drop table if exists users;

CREATE TABLE IF NOT EXISTS users (
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name  VARCHAR(255) NOT NULL,
    user_email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (user_email)
);


CREATE TABLE IF NOT EXISTS items (
    item_id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    item_name         varchar(100) NOT NULL,
    item_description  varchar(4000) NOT NULL,
    item_is_available Boolean NOT NULL,
    owner_id          BIGINT NOT NULL,
    url               VARCHAR(1000),
    request_id        BIGINT,
    CONSTRAINT fk_items_to_users FOREIGN KEY(owner_id) REFERENCES users(user_id), UNIQUE(item_id, url)
);

CREATE TABLE IF NOT EXISTS bookings (
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE not null ,
    end_date   TIMESTAMP WITHOUT TIME ZONE not null ,
    booker_id  BIGINT not null ,
    item_id    bigint not null ,
    status     varchar(50),
    CONSTRAINT fk_bookings_to_items FOREIGN KEY(item_id) REFERENCES items(item_id),
    CONSTRAINT fk_bookings_to_users FOREIGN KEY(booker_id) REFERENCES users(user_id)
);

create table if not exists requests (
    id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    description  varchar(4000) not null ,
    requester_id bigint not null ,
    CONSTRAINT fk_requests_to_users FOREIGN KEY(requester_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS comments (
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    text       varchar(4000) not null ,
    item_id    bigint not null ,
    author_id  bigint not null ,
    created    TIMESTAMP WITHOUT TIME ZONE not null ,
    CONSTRAINT fk_comments_to_items FOREIGN KEY(item_id) REFERENCES items(item_id),
    CONSTRAINT fk_comments_to_users FOREIGN KEY(author_id) REFERENCES users(user_id)
);